accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "1000000000uqsar"]
  - name: bob
    coins: ["10000token", "100000000stake", "1000000000uqsar"]
validator:
  name: alice
  staked: "100000000uqsar"
genesis:
  app_state:
    staking:
      params:
        bond_denom: uqsar
    orion:
      params:
        enabled: true
        lp_epoch_id: minute #override day for testing
        mgmt_fee_per: '0.003000000000000000'
        perf_fee_per: '0.020000000000000000'
    qbank:
      params:
        enabled: true
        min_orion_epoch_denom_dollar_deposit: '100.000000000000000000'
        orion_epoch_identifier: minute #override day for testing
        white_listed_denoms_in_orion:
          - onehop_osmo: ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC
            onehop_quasar: ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC
            origin_name: uatom
          - onehop_osmo: ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC
            onehop_quasar: uqsar
            origin_name: uqsar
#client:
#  openapi:
#    path: "docs/client/static/openapi/openapi.yml"
#  vuex:
#    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake", "10000uqsar"]
