[workspace]

members = [
    "contracts/cw-4626",
    "contracts/strategy",
    "contracts/ibc-transfer-test",
    "contracts/intergamm-bindings-test",
    "contracts/qoracle-bindings-test",
    "packages/intergamm-bindings",
    "packages/quasar-traits",
    "packages/quasar-types"
]