name: Test Quasar

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# This workflow makes x86_64 binaries for linux.
# TODO: add darwin later
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - name: Run all tests
        run: |
          make test-cover
      - name: Code coverage report
        uses: codecov/codecov-action@v1.5.2
